#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Pipeline for ORIGINAL-LENGTH positive peaks + GC-preserved shuffled negatives.

Key changes relative to the old script:
  1) Positive peaks are NOT expanded around summit.
  2) Train/validation/test splits are made directly from the original peak coordinates.
  3) Negative sequences are generated by shuffling each positive sequence, so length and
     mononucleotide composition (and therefore GC content) are preserved exactly.

Outputs:
  POS:
    {bed_out_dir}/{name}.original_length.bed
    {bed_out_dir}/{name}.narrowPeak.train.bed (+ validation/test)
    {fasta_out_dir}/{name}.original_length.fasta
    {fasta_out_dir}/{name}.narrowPeak.train.bed.fasta (+ validation/test)

  NEG (sequence-space negatives; not real genomic loci):
    {neg_out_dir}/{name}.shuffledGCmatch.original_length.fasta
    {neg_out_dir}/{name}.shuffledGCmatch.original_length.train.fasta (+ validation/test)

  Placeholder NEG BEDs for compatibility:
    {bed_out_dir}/{name}.narrowPeak.train.Neg.bed (+ validation/test)
    {bed_out_dir}/{name}.narrowPeak.train.withNeg.bed (+ validation/test)
    {bed_out_dir}/{name}.narrowPeak.train.Neg_Part1.bed ... Neg_Part4.bed

  POSNEG FASTA:
    {posneg_out_dir}/{name}.narrowPeak.train.posneg.fasta (+ validation/test)

Important:
  - The FASTA negatives are the real outputs here.
  - The NEG BEDs are placeholders that reuse the original positive coordinates only for
    bookkeeping / compatibility with downstream code expecting BED label files.
  - Do NOT use the placeholder NEG BEDs to extract genomic sequence.
"""

import gzip
import shutil
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import subprocess


# =========================================================
# helpers
# =========================================================
def require_file(p: str, label: str = ""):
    pth = Path(p)
    if not pth.is_file():
        raise FileNotFoundError("{} missing file: {}".format(label, pth))


def require_dir(p: str, label: str = ""):
    pth = Path(p)
    if not pth.is_dir():
        raise FileNotFoundError("{} missing dir: {}".format(label, pth))


def ensure_dir(p: str):
    Path(p).mkdir(parents=True, exist_ok=True)


def which_or_raise(exe: str):
    if shutil.which(exe) is None:
        raise EnvironmentError("Missing executable in PATH: {}".format(exe))


def run(cmd: str):
    print("[RUN] {}".format(cmd))
    subprocess.run(cmd, shell=True, check=True)


def gunzip_to_temp(gz_path: str, out_path: str):
    with gzip.open(gz_path, "rb") as f_in, open(out_path, "wb") as f_out:
        shutil.copyfileobj(f_in, f_out)


def maybe_decompress(path_in: str, work_dir: str) -> str:
    p = Path(path_in)
    if p.suffix == ".gz":
        out_path = str(Path(work_dir) / p.name.replace(".gz", ""))
        gunzip_to_temp(str(p), out_path)
        return out_path
    return str(p)


def write_fasta_from_df(df: pd.DataFrame, fasta_path: str, header_col: str = "header", seq_col: str = "sequence"):
    ensure_dir(str(Path(fasta_path).parent))
    with open(fasta_path, "w") as fout:
        for _, row in df.iterrows():
            fout.write(">{header}\n{seq}\n".format(header=row[header_col], seq=row[seq_col]))


def gc_fraction(seq: str) -> float:
    seq = str(seq).upper()
    valid = [b for b in seq if b in set(["A", "C", "G", "T"])]
    if len(valid) == 0:
        return np.nan
    gc = sum([1 for b in valid if b in set(["G", "C"])])
    return float(gc) / float(len(valid))


def read_bedtools_tab(tab_file: str) -> pd.DataFrame:
    rows = []
    with open(tab_file, "r") as fin:
        for line in fin:
            line = line.rstrip("\n")
            if not line:
                continue
            name, seq = line.split("\t", 1)
            rows.append((name, seq))
    return pd.DataFrame(rows, columns=["name", "sequence"])


def bed_to_fasta_df(bed_file: str, genome_fa: str, work_dir: str, prefix: str) -> pd.DataFrame:
    tab_out = str(Path(work_dir) / (prefix + ".bedtools.tab"))
    run("bedtools getfasta -fi {genome} -bed {bed} -name -tab > {out}".format(
        genome=genome_fa,
        bed=bed_file,
        out=tab_out,
    ))
    return read_bedtools_tab(tab_out)


def write_bed(df: pd.DataFrame, bed_path: str, cols: List[str]):
    ensure_dir(str(Path(bed_path).parent))
    df.loc[:, cols].to_csv(bed_path, sep="\t", header=False, index=False)


def split_by_chrom(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    val = df[df["chrom"] == "chr4"].copy()
    test = df[df["chrom"].isin(["chr8", "chr9"])].copy()
    train = df[~df["chrom"].isin(["chr4", "chr8", "chr9"])].copy()
    return train, val, test


def cat_fastas(f1: str, f2: str, out_fa: str):
    ensure_dir(str(Path(out_fa).parent))
    with open(out_fa, "w") as fout:
        for fp in [f1, f2]:
            with open(fp, "r") as fin:
                shutil.copyfileobj(fin, fout)


# =========================================================
# positive peaks (original length)
# =========================================================
def load_original_narrowpeak(narrowpeak_in: str) -> pd.DataFrame:
    df = pd.read_csv(narrowpeak_in, sep="\t", header=None)
    if df.shape[1] < 10:
        raise ValueError("{} has {} cols; expected >=10 for narrowPeak.".format(narrowpeak_in, df.shape[1]))

    df = df.iloc[:, :10].copy()
    df.columns = [
        "chrom", "start", "end", "name", "score", "strand",
        "signalValue", "pValue", "qValue", "summit"
    ]
    df["start"] = df["start"].astype(int)
    df["end"] = df["end"].astype(int)
    df["peak_id"] = ["pos_{:07d}".format(i) for i in range(df.shape[0])]
    return df


def write_positive_outputs(df_pos: pd.DataFrame, cfg: Dict[str, str]):
    name = cfg["name"]
    genome_fa = cfg["genome_fa"]
    work_dir = cfg["work_dir"]
    bed_out_dir = cfg["bed_out_dir"]
    fasta_out_dir = cfg["fasta_out_dir"]

    ensure_dir(bed_out_dir)
    ensure_dir(fasta_out_dir)

    pos_full_bed = str(Path(bed_out_dir) / (name + ".original_length.bed"))
    write_bed(df_pos, pos_full_bed, [
        "chrom", "start", "end", "peak_id", "score", "strand",
        "signalValue", "pValue", "qValue", "summit"
    ])

    train_df, val_df, test_df = split_by_chrom(df_pos)

    pos_train_bed = str(Path(bed_out_dir) / (name + ".narrowPeak.train.bed"))
    pos_val_bed = str(Path(bed_out_dir) / (name + ".narrowPeak.validation.bed"))
    pos_test_bed = str(Path(bed_out_dir) / (name + ".narrowPeak.test.bed"))

    for dfi, out_bed in [(train_df, pos_train_bed), (val_df, pos_val_bed), (test_df, pos_test_bed)]:
        write_bed(dfi, out_bed, [
            "chrom", "start", "end", "peak_id", "score", "strand",
            "signalValue", "pValue", "qValue", "summit"
        ])

    pos_full_seq = bed_to_fasta_df(pos_full_bed, genome_fa, work_dir, name + ".pos_full")
    pos_full = df_pos.merge(pos_full_seq, left_on="peak_id", right_on="name", how="left")
    pos_full["header"] = pos_full["peak_id"] + "|" + pos_full["chrom"] + ":" + pos_full["start"].astype(str) + "-" + pos_full["end"].astype(str)
    pos_full["gc"] = pos_full["sequence"].map(gc_fraction)

    pos_full_fa = str(Path(fasta_out_dir) / (name + ".original_length.fasta"))
    write_fasta_from_df(pos_full, pos_full_fa)

    out = {
        "pos_full_bed": pos_full_bed,
        "pos_full_fa": pos_full_fa,
        "pos_train_bed": pos_train_bed,
        "pos_val_bed": pos_val_bed,
        "pos_test_bed": pos_test_bed,
        "pos_train_fa": str(Path(fasta_out_dir) / (Path(pos_train_bed).name + ".fasta")),
        "pos_val_fa": str(Path(fasta_out_dir) / (Path(pos_val_bed).name + ".fasta")),
        "pos_test_fa": str(Path(fasta_out_dir) / (Path(pos_test_bed).name + ".fasta")),
    }

    for subset_df, out_fa in [(train_df, out["pos_train_fa"]), (val_df, out["pos_val_fa"]), (test_df, out["pos_test_fa"])]:
        sub = pos_full[pos_full["peak_id"].isin(subset_df["peak_id"])].copy()
        write_fasta_from_df(sub, out_fa)

    return out, pos_full, train_df, val_df, test_df


# =========================================================
# shuffled negatives preserving GC exactly
# =========================================================
def shuffle_sequence(seq: str, rng: np.random.RandomState, max_tries: int = 20) -> str:
    seq = str(seq).upper()
    arr = np.array(list(seq), dtype="<U1")
    if len(arr) <= 1:
        return seq

    for _ in range(max_tries):
        arr2 = arr.copy()
        rng.shuffle(arr2)
        shuffled = "".join(arr2.tolist())
        if shuffled != seq:
            return shuffled
    return "".join(arr.tolist())


def build_shuffled_negatives(df_pos_full: pd.DataFrame, seed: int = 19951124) -> pd.DataFrame:
    rng = np.random.RandomState(seed)
    df = df_pos_full.copy()

    shuffled_list = []
    used_sequences = set(df["sequence"].astype(str).tolist())

    for _, row in df.iterrows():
        seq = str(row["sequence"])
        new_seq = shuffle_sequence(seq, rng)
        n_try = 0
        while new_seq in used_sequences and n_try < 20:
            new_seq = shuffle_sequence(seq, rng)
            n_try += 1
        used_sequences.add(new_seq)
        shuffled_list.append(new_seq)

    df["neg_sequence"] = shuffled_list
    df["neg_gc"] = df["neg_sequence"].map(gc_fraction)
    df["gc_abs_diff"] = (df["gc"] - df["neg_gc"]).abs()
    df["header"] = df["peak_id"] + "|NEG_SHUFFLED|" + df["chrom"] + ":" + df["start"].astype(str) + "-" + df["end"].astype(str)
    df["sequence"] = df["neg_sequence"]
    return df


def make_placeholder_negative_label_bed(df_neg: pd.DataFrame) -> pd.DataFrame:
    out = pd.DataFrame()
    out[0] = df_neg["chrom"].astype(str)
    out[1] = df_neg["start"].astype(int)
    out[2] = df_neg["end"].astype(int)
    out[3] = df_neg["peak_id"].astype(str) + "_NEG_SHUFFLED"
    out[4] = 0
    out[5] = "."
    out[6] = 0
    out[7] = "NA"
    out[8] = "NA"
    out[9] = "NA"
    return out


def write_neg_parts(train_neg_bed: str):
    df = pd.read_csv(train_neg_bed, sep="\t", header=None)
    df = df.sample(frac=1.0, random_state=0).reset_index(drop=True)
    split_size = len(df) // 4
    parts = [
        df.iloc[:split_size],
        df.iloc[split_size:2 * split_size],
        df.iloc[2 * split_size:3 * split_size],
        df.iloc[3 * split_size:],
    ]
    for i, part in enumerate(parts, start=1):
        part.to_csv(train_neg_bed[:-4] + ".Neg_Part{}.bed".format(i), sep="\t", header=None, index=False)


# =========================================================
# main
# =========================================================
def validate_config(cfg: Dict[str, str]):
    require_file(cfg["narrowpeak_gz"], "CONFIG")
    require_file(cfg["genome_fa"], "CONFIG")
    require_dir(cfg["neg_out_dir"], "CONFIG")

    ensure_dir(cfg["work_dir"])
    ensure_dir(cfg["bed_out_dir"])
    ensure_dir(cfg["fasta_out_dir"])
    ensure_dir(cfg["posneg_out_dir"])

    which_or_raise("bedtools")


def main(cfg: Dict[str, str]):
    validate_config(cfg)

    narrowpeak_txt = maybe_decompress(cfg["narrowpeak_gz"], cfg["work_dir"])
    df_pos = load_original_narrowpeak(narrowpeak_txt)
    paths, df_pos_full, train_pos, val_pos, test_pos = write_positive_outputs(df_pos, cfg)

    df_neg = build_shuffled_negatives(df_pos_full, seed=int(cfg.get("shuffle_seed", 19951124)))

    name = cfg["name"]
    neg_out_dir = cfg["neg_out_dir"]
    bed_out_dir = cfg["bed_out_dir"]
    posneg_out_dir = cfg["posneg_out_dir"]

    full_neg_fa = str(Path(neg_out_dir) / (name + ".shuffledGCmatch.original_length.fasta"))
    write_fasta_from_df(df_neg, full_neg_fa)

    train_neg, val_neg, test_neg = split_by_chrom(df_neg)

    train_neg_fa = str(Path(neg_out_dir) / (name + ".shuffledGCmatch.original_length.train.fasta"))
    val_neg_fa = str(Path(neg_out_dir) / (name + ".shuffledGCmatch.original_length.validation.fasta"))
    test_neg_fa = str(Path(neg_out_dir) / (name + ".shuffledGCmatch.original_length.test.fasta"))
    write_fasta_from_df(train_neg, train_neg_fa)
    write_fasta_from_df(val_neg, val_neg_fa)
    write_fasta_from_df(test_neg, test_neg_fa)

    train_neg_bed = str(Path(bed_out_dir) / (name + ".narrowPeak.train.Neg.bed"))
    val_neg_bed = str(Path(bed_out_dir) / (name + ".narrowPeak.validation.Neg.bed"))
    test_neg_bed = str(Path(bed_out_dir) / (name + ".narrowPeak.test.Neg.bed"))

    make_placeholder_negative_label_bed(train_neg).to_csv(train_neg_bed, sep="\t", header=False, index=False)
    make_placeholder_negative_label_bed(val_neg).to_csv(val_neg_bed, sep="\t", header=False, index=False)
    make_placeholder_negative_label_bed(test_neg).to_csv(test_neg_bed, sep="\t", header=False, index=False)

    for pos_bed, neg_bed in [
        (paths["pos_train_bed"], train_neg_bed),
        (paths["pos_val_bed"], val_neg_bed),
        (paths["pos_test_bed"], test_neg_bed),
    ]:
        pos_df = pd.read_csv(pos_bed, sep="\t", header=None)
        neg_df = pd.read_csv(neg_bed, sep="\t", header=None)
        withneg_path = pos_bed[:-4] + ".withNeg.bed"
        pd.concat([pos_df, neg_df], axis=0).to_csv(withneg_path, sep="\t", header=False, index=False)

    write_neg_parts(train_neg_bed)

    train_posneg = str(Path(posneg_out_dir) / (name + ".narrowPeak.train.posneg.fasta"))
    val_posneg = str(Path(posneg_out_dir) / (name + ".narrowPeak.validation.posneg.fasta"))
    test_posneg = str(Path(posneg_out_dir) / (name + ".narrowPeak.test.posneg.fasta"))

    cat_fastas(paths["pos_train_fa"], train_neg_fa, train_posneg)
    cat_fastas(paths["pos_val_fa"], val_neg_fa, val_posneg)
    cat_fastas(paths["pos_test_fa"], test_neg_fa, test_posneg)

    summary_path = str(Path(cfg["work_dir"]) / (name + ".shuffledGCmatch.summary.tsv"))
    df_neg.loc[:, ["peak_id", "chrom", "start", "end", "gc", "neg_gc", "gc_abs_diff"]].to_csv(
        summary_path, sep="\t", index=False
    )

    print("\n[DONE]")
    print("POS full fasta:", paths["pos_full_fa"])
    print("NEG full fasta:", full_neg_fa)
    print("Train/val/test posneg:", train_posneg, val_posneg, test_posneg)
    print("Shuffled GC summary:", summary_path)
    print("[NOTE] NEG BEDs are placeholders only; use the NEG FASTA files as the real shuffled negatives.")


# =========================================================
# EDIT CONFIG ONLY
# =========================================================
CONFIG = {
    "name": "fullard_DLPFC_neurons.optimal_peak",
    "narrowpeak_gz": "../peak_files/fullard_DLPFC/fullard_DLPFC_neurons.optimal_peak.narrowPeak.gz",
    "genome_fa": "../../genome/hg38.fa",

    "shuffle_seed": 19951124,

    "work_dir": "./_work_fullard_DLPFC_original_length_shuffled_neg",
    "bed_out_dir": "../original_length_peaks_hg38",
    "fasta_out_dir": "../original_length_peaks_fasta_hg38",
    "neg_out_dir": "/media/zihengc/T7/THP1_machinelearning/background_negatives_original_length_hg38",
    "posneg_out_dir": "../positive_negative_original_length_hg38",
}


if __name__ == "__main__":
    main(CONFIG)
